name: CI

on:
  push:
    branches: "*"
    paths-ignore: 
      - 'README.md'
      
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [api-schema, backend, web, foreign-lib, admin-web]
    steps:
      # Setup Nix envirionment
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: cachix/cachix-action@v14
        with:
          name: katsujukou-github
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: nicknovitski/nix-develop@v1
      - run: nix develop --extra-experimental-features "nix-command flakes"

      # Run CI jobs
      - name: Install
        run: spago install && pnpm -F './${{ matrix.target }}' install
        env:
          NPM_CONFIG_USERCONFIG: ".github/workflows/${{ matrix.target }}/.npmrc"

      - name: Compile
        run: pnpm -F './${{ matrix.target}}' run compile
        
      - name: Test
        run: pnpm -F './${{ matrix.target }}' run test

      - name: Check
        run: pnpm -F './${{ matrix.target }}' run check
        